name: VitalPlayerTime
version: @version@
main: dev.meinel.leo.vitalplayertime.VitalPlayerTime
api-version: 1.17
authors: [ Leopold Meinel ]
description: Gives players the ability to open a crafting interface.
commands:
  ptime:
    description: "Main command"
    usage: "/ptime"
permissions:
  vitalplayertime.set:
    description: "Permission to change playertime"
    default: op